### ISSUE TITLE
Unable to create agent

### ISSUE THREAD

**Issue by ekanath25** [axa-group/nlp.js-app#43]
**Describe the bug**
I tried to launch the app from localhost. The backend and client app started successfully. When I try to create agent its loding and  didn't give a response 

**To Reproduce**
1. Start the backend server
2. Start the client app
3. Try to create agent

**Screenshots**
![image](https://user-images.githubusercontent.com/20681626/61864628-5d76e300-aeef-11e9-8ab2-f8f40f0d4f29.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome
 - node 10.15

**Additional context**
Please help me to solve this issue

**Comment by ericzon** [comment]
Hello @ekanath25 I've just cloned the latest version of the repository and started from scratch. I tried with your same version of Node.JS and Chrome (sorry but I don't have Windows). It worked well. I've also tried with Firefox.

After clone the repo, rename the file .envexample to .env and start with npm start.
In this try, use default port 3000.

**Comment by ericzon** [comment]
@ekanath25 Closing this as master is working and there are no more comments about this.
