### ISSUE TITLE
Include code integrations to the intents

### ISSUE THREAD

**Issue by ramonck** [axa-group/nlp.js-app#52]
I would like to know if it`s possible to include javascript code integrations into the intents before giving the response and incorporate that into the response for example: check the weather in the a site and come back with the weather results for the city and in the response respond with the weather results, how can this work with this tool?

Thanks for the work by the way it looks very similar to the Dialogflow by the way which is the best UI out there, very nice job.

**Comment by ericzon** [comment]
First of all, thanks @ramonck for your kind words.

Regarding to your question, a PR related with this was accepted in nlp.js repository (but there's no new release yet).
It allows to configure a list of actions to be applied to an answer (can be sync or async) and are related with an intent. I added some tests to document.

https://github.com/axa-group/nlp.js/pull/296

Anyway, these kind of interactions doesn't feel to me the best approach (for **this** dashboard), although in a fast demo can give a great appearance, depending on the actions added, your intents can become less generics. For me the best option should be implement this in the flow.

**Comment by ericzon** [comment]
Closing this ticket due to inactivity (moreover, it has been already answered)
