### ISSUE TITLE
Hapi module deprecation

### ISSUE THREAD

**Issue by tassoman** [axa-group/nlp.js-app#57]
Running `npm update` you get various deprecation notifications about hapi and its dependencies. I paste the most representative:

> npm WARN deprecated hapi@17.8.5: This module has moved and is now available at @hapi/hapi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
 

**To Reproduce**
1. `git clone` this repository
2. `npm update` the libraries
3. read npm logging

 - OS: Xubuntu
 - Node v12.9.1
 - Npm v6.11.2

**Comment by ericzon** [comment]
@hapi/hapi dependency updated to 18.4.0, warning disappeared.

**Comment by tassoman** [comment]
Yes, sir!
