### ISSUE TITLE
Empty default fallback answer

### ISSUE THREAD

**Issue by tassoman** [axa-group/nlp.js-app#59]
I tried to customize the global setting for _default fallback answers_ in italian language but when I write unrecognised text in the chat demo, the answer is an empty baloon. Neither Agent's fallback responses are working.

1. Go to settings, change language, add some global fallback answers. Save.
2. Go to Agent's edit page, edit fallback answers with different strings. Save.
3. Add a domain. Add an intent and re-train.
4. write some random text in the demo chat pane: «sdafsofijaso»
5. any of the strings is displayed as answer, only empty baloon

I expected to get one of the answers from Agent's fallback.
Then I would like to delete that answer and get the global answers.
If any of them is set, three dots «...» can be enough.

![Screenshot_2019-11-07 Agent Provagent](https://user-images.githubusercontent.com/92727/68381910-f2c27e00-0152-11ea-9d2c-644f5572e018.png)

 - OS: Xubuntu
 - Browser: firefox latest stable
 - Node: v12.9.1
 - Npm: 6.11.2

**Comment by tassoman** [comment]
The yellow background is my default preference in the browser. That means `body { background-color: white;}` css rule is missing :slightly_smiling_face:

**Comment by ericzon** [comment]
Thanks for reporting this @tassoman , I can have it soon working. Missing css is not a bug is a feature :))
Ok, let's fix it too.

**Comment by ericzon** [comment]
Pulll and try again @tassoman ;)

**Comment by tassoman** [comment]
Thank you! Now default fallback answers are working like expected :frog:
