### ISSUE TITLE
cross origin blocked request (CORS) running on remote host

### ISSUE THREAD

**Issue by tassoman** [axa-group/nlp.js-app#60]
I'm trying to run the app wild on a remote server, using a different port than 3000 (3010).
That's because I'd like to run it by [pm2](https://pm2.keymetrics.io/) then reverse proxy it under Apache. So I'm configuring a different environment, because of 3000 port already configured by another app: 

`./.env`
```bash
NODE_ENV=production
MONGO_URL=mongodb://localhost:27017/nlpjs
LOG_LEVEL=info
PORT=3010
```
`./client/.env`
```bash
SETTINGS_URL=http://10.11.2.80:3010
API_URL=http://10.11.2.80:3010
PUBLIC_PATH_PREFIX=
```
After I ran `npm start`, I can reach the web interface but it feels bad, missing APIs.
Reading browser's console I found four calls to http://localhost:3000/swagger2.json blocked by CORS rule. 
In real life that JSON file can be found at http://10.11.2.80:3010/swagger2.json
Looks like something is hardcoded somehow.

1. clone this repo
2. edit `.env` files according remote host
3. `npm install` then `npm start` inside project root
4. Open your remote host webpage and browser's console.

I've expected that editing the environment was helpful to run things remotely.

 - OS: Centos7
 - Browser: latest firefox
 - Version: master
 - Node: v12.9.1
 - NPM: 6.11.2

**Comment by tassoman** [comment]
One more thing, «Agent head missing» error page is missing a link to configuration instructions.
I can only read a text ending with: `For configuration instruction go to here:"

**Comment by ericzon** [comment]
I've followed the steps and now I'm running the dashboard in port 3010 without problems.
To apply the changes in ./client/.env you need to run: npm run build. This will generate a /build folder with the new values. After this, you need to replace the content of /public folder by the content of /build.

```
cd client
npm run build
cd ..
mv public public_old
mv client/build public
```

**Comment by tassoman** [comment]
Clear, that’s why seemed to me a «default» configuration.
So I've rebuilt the client but I got an error while building:

> ERROR in ./\~/css-loader!./\~/sass-loader/lib/loader.js!./app/components/Table2/table.style.scss
Module build failed: Error: Cannot find module 'node-sass'

`npm start` is running and I've created a test Agent. When I click «Domains» I get an empty page and the same error in browser's console:

> Unhandled promise rejection error: "Module build failed: Error: Cannot find module 'node-sass'

I guess solution maybe `yarn add node-sass` or `npm install node-sass --save-dev` but doing that my `packages.json` gets forked

**Comment by ericzon** [comment]
This means your don't have installed the dependencies inside ./client folder. if you check the package.json in that folder, you will see the node-sass as dependency.

**Comment by tassoman** [comment]
True, thank you!
